experiment_name: revival_baseline
seed: 42
overwrite: false
save_plots: true
live_monitoring: false  # Enable with --monitor or set true here
monitor_interval_seconds: 2

num_episodes: 2000
max_actions: 2000
save_interval: 500

num_players: 2
size: 1
bot_types:
 - "Random"             # "Neutral", "Random"
#action_masking: False  # Hide or limit selection of actions such as skip

num_layers: 5
hidden_dim_max: 512
hidden_dim_min: 128

batch_size: 64
gamma: 0.95
learning_rate: 0.005
tau: 0.05
optimize_ratio: 2         # on modulus batch size, how many batches to train on
target_update_freq: 100

decay_type: "lin"         # lin / geo / osc
epsilon_max: 1
epsilon_min: 0.1
epsilon_decay: 0.99997    # for geo only
num_oscillations: 10      # for osc only

render_final_results: true
load_checkpoint: "dqn_model_best.pth"
eval_only: false
show_board: false
num_eval: 20
